### ISSUE TITLE
make basic samples smaller

### ISSUE THREAD

**Issue by enricosada** [dotnet/dotnet-template-samples#13]
The first samples (basic, etc) is a copy of aspnet web template.
While is good, there are lot of useless files, is really hard to understand what's needed for THE TEMPLATE, and what's there just because is an aspnet core app.

These are the first templates you read, and are really complex.

Is possibile to use normal (hello world) console app an lib there too?

**Comment by sayedihashimi** [comment]
Agreed, let's convert them to console projects instead.

**Comment by sayedihashimi** [comment]
I have updated all the templates to be a console project with the exception of https://github.com/dotnet/dotnet-template-samples/tree/master/03-optional-page. I wanted to leave a web template in there.

I think the issue here has been addressed so I'm going to close this. If you feel that I've misunderstood please reopen with some details.

**Comment by enricosada** [comment]
awesome, thx @sayedihashimi
